title: Shelanah Rahman # your name (or website title) here
# logo: "/images/logo.png?raw=true" your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a final-year undergraduate student at the University of Melbourne, majoring in Data Science as part of the Bachelor of Science. This portfolio includes projects
  that I did during in Uni or I did just for fun. Other than coding and data analytics, I enjoy reading, sketching and travelling! 
  
 
  <a href="https://www.linkedin.com/in/shelanah-rahman-09426b188">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-194594011-1 # your Google Analytics tracking ID here
